<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Project3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Project3_files/libs/clipboard/clipboard.min.js"></script>
<script src="Project3_files/libs/quarto-html/quarto.js"></script>
<script src="Project3_files/libs/quarto-html/popper.min.js"></script>
<script src="Project3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Project3_files/libs/quarto-html/anchor.min.js"></script>
<link href="Project3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Project3_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Project3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Project3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Project3_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Project3</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="project-housing-price-in-ames" class="level2">
<h2 class="anchored" data-anchor-id="project-housing-price-in-ames">Project Housing Price in Ames</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This project will analyze the housing price in Ames. In the previous project, we have discussed that the model SalePrice~Gr.Liv.Area is not really reasonable because the value of the <span class="math inline">\(R^2\)</span> is around 0.5 which shows that the fitted model is not really close to the actual data so the model is not reasonably good. But when the model was added with Neighborhood explanatory variable (SalePrice ~ Gr.Liv.Area + Neighborhood model), the value of <span class="math inline">\(R^2\)</span> has increase a lot from 0.5 to 0.7 which is pretty strong. So SalePrice ~ Gr.Liv.Area + Neighborhood model seems to be the best model for the ames dataset. So now, this project will use regression assumptions to clarify if the SalePrice ~ Gr.Liv.Area + Neighborhood model reasonable or not.</p>
<p>First, let’s look at the graph of the ames SalePrice ~ Gr.Liv.Area + Neighborhood model:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project3_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There are a few unusual points in the graph which may make the data not accurate. So I create a new dataset called <strong>ames1</strong> that eliminate all unusual points which is when Gr.Liv.Area is larger than 4000 sq ft:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project3_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now I will look at 4 conditions of regression assumptions which is linear relationship, independent errors, normal errors, and equal variances. If the model above fits with all the conditions, the model is reasonable.</p>
<ol type="1">
<li><strong>Linear relationship</strong>: From the scatter plot, we can tell that the residual is not distributed linearly because in the first half of the graph, it decreases while the second half, it starts to increase to the right.</li>
<li><strong>Independent errors</strong>: The requirement that the residuals be independent simply means that the residuals should not be related to each other which means that the shape of the graph shouldn’t have any pattern. However, according to the scatter plot above, we can see that the residual starts to spread out from the left to the right which creates a trumpet shape. So the residuals are not independent.</li>
<li><strong>Normal errors:</strong> To qualify this requirement, the shape of the distribution of these errors should be a normal distribution (centered at 0) which means that histogram of the residuals should curve into a straight line. Let’s check:</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project3_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the graph, I can tell that the model doesn’t has normal distribution because it doesn’t lie on the straight line. It curves up at the end of the graph (on the right) and there is some data that is under the straight line on the left of the graph.</p>
<ol start="4" type="1">
<li><strong>Equal variance</strong> <strong>(homoskedasticity)</strong>: means that the standard deviation of that normal distribution can be anything, but it should be the same everywhere. In this cases, we can see that the standard deviation on the right tends to be higher than the standard deviation on the left (according the the scatter plot) So it means that this model doesn’t qualify the equal variance requirement.</li>
</ol>
<p>Therefore, from these 4 condition, the SalePrice ~ Gr.Liv.Area + Neighborhood model seems to violate with the regression assumptions.</p>
<p>So to find a reasonable model, we need to modify the model to fit with the regression assumptions by using transformations: <code>log(</code>SalePrice<code>)</code> ~Gr.Liv.Area + Neighborhood.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project3_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>According to the new scatter plot, there is a <strong>linear relationship, independent errors</strong> (the shape of the graph doesn’t have any pattern which means that the plot doesn’t have a trumpet shape) and <strong>equal variance</strong> (the standard deviation is the same everywhere) And the new model <strong>distribute normally</strong> because it lies mostly on a straight line (the graph below)</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project3_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Therefore, the new model has fulfill the regression assumptions.</p>
<p>Now we will compare the <span class="math inline">\(R^2\)</span> of the 2 models to see which model is more precise.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7555103</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.759322</code></pre>
</div>
</div>
<p>So we see that the <span class="math inline">\(R^2\)</span> of model 1 = 0.7555103 and the <span class="math inline">\(R^2\)</span> of model 2 = 0.759322. The <span class="math inline">\(R^2\)</span> of model 2 is higher than the <span class="math inline">\(R^2\)</span> of model 1. Therefore, the model 2 provides a better <span class="math inline">\(R^2\)</span>.</p>
<p>Now we calculate the precision of the coefficience of 2 models:</p>
<ul>
<li>The confident interval of model 1:</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                            2.5 %      97.5 %
(Intercept)           67429.90437  97956.3864
Gr.Liv.Area              77.64986     84.5953
NeighborhoodBlueste  -61386.45642  -4975.5464
NeighborhoodBrDale   -87689.84826 -47420.9864
NeighborhoodBrkSide  -74355.84404 -41875.6966
NeighborhoodClearCr  -34078.19429   2997.8407
NeighborhoodCollgCr  -17464.04290  12946.4166
NeighborhoodCrawfor  -31247.53651   1447.5841
NeighborhoodEdwards  -71733.67582 -40748.4763
NeighborhoodGilbert  -39197.44801  -7878.3794
NeighborhoodGreens   -13732.64418  47650.6420
NeighborhoodGrnHill   27843.90676 139869.9462
NeighborhoodIDOTRR   -93224.17976 -60201.8475
NeighborhoodLandmrk -130658.44619  25108.5442
NeighborhoodMeadowV  -92675.26408 -54265.4044
NeighborhoodMitchel  -44339.96969 -12053.2072
NeighborhoodNAmes    -57328.26130 -27492.8662
NeighborhoodNoRidge   21219.81841  56239.4944
NeighborhoodNPkVill  -64449.03118 -21362.6078
NeighborhoodNridgHt   65987.41664  97479.1197
NeighborhoodNWAmes   -47247.48395 -15319.9099
NeighborhoodOldTown  -90153.25788 -59580.2465
NeighborhoodSawyer   -57677.39595 -26146.9123
NeighborhoodSawyerW  -44764.23171 -12733.3114
NeighborhoodSomerst    1275.53201  32376.9790
NeighborhoodStoneBr   65311.69287 101509.5977
NeighborhoodSWISU    -98592.62676 -62160.6132
NeighborhoodTimber     7732.33932  41888.5924
NeighborhoodVeenker   -3321.34226  39352.3894</code></pre>
</div>
</div>
<ul>
<li>The confident interval of model 2:</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                            2.5 %        97.5 %
(Intercept)         11.5119556630 11.6684991217
Gr.Liv.Area          0.0004012132  0.0004368302
NeighborhoodBlueste -0.3645543404 -0.0752724328
NeighborhoodBrDale  -0.5998704079 -0.3933668583
NeighborhoodBrkSide -0.5001146102 -0.3335525214
NeighborhoodClearCr -0.1982545949 -0.0081242438
NeighborhoodCollgCr -0.1135123179  0.0424361631
NeighborhoodCrawfor -0.1999721984 -0.0323077013
NeighborhoodEdwards -0.4843423806 -0.3254465638
NeighborhoodGilbert -0.2041987693 -0.0435908318
NeighborhoodGreens  -0.0653286984  0.2494521500
NeighborhoodGrnHill  0.0628705020  0.6373534589
NeighborhoodIDOTRR  -0.7058733465 -0.5365308689
NeighborhoodLandmrk -0.7149957676  0.0837960282
NeighborhoodMeadowV -0.6856979904 -0.4887276264
NeighborhoodMitchel -0.2630759539 -0.0975055661
NeighborhoodNAmes   -0.3444100782 -0.1914105963
NeighborhoodNoRidge -0.0475538224  0.1320312731
NeighborhoodNPkVill -0.3697363536 -0.1487840104
NeighborhoodNridgHt  0.1540435510  0.3155367786
NeighborhoodNWAmes  -0.2526878524 -0.0889594259
NeighborhoodOldTown -0.5960602822 -0.4392782154
NeighborhoodSawyer  -0.3563962187 -0.1947041198
NeighborhoodSawyerW -0.2580773460 -0.0938189475
NeighborhoodSomerst -0.0269093934  0.1325825541
NeighborhoodStoneBr  0.1218679231  0.3074951173
NeighborhoodSWISU   -0.5832953638 -0.3964676319
NeighborhoodTimber  -0.0179376087  0.1572197507
NeighborhoodVeenker -0.0732320701  0.1456039401</code></pre>
</div>
</div>
<p>From the calculation above, we can see that the confident interval of model 1 is wider than the confident interval of model 2. For example, the confident interval of Gr.Liv.Area in model 1 is between 77.64986 and 84.5953 (6.94544 difference)while the confident interval of Gr.Liv.Area in model 2 is between 0.0004012132 and 0.0004368302(3.5617e-05 difference). From this example, we can see that the confident interval in model 1 is wider than model 2 which means that the model 2 is more precise than the model 1.</p>
<p>Now, I will pick Gr.Liv.Area = 2000 and Neighborhood = Somerst and use regression equation to predict its sale price.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 12.48111 12.08752 12.87469</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 263316</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 177641</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 390307.4</code></pre>
</div>
</div>
<p>Using the regression equation, the sale price will be $263316. And we are 95% confidence that the price of the house having 2000 square feet ground living area in Somerst neighborhood are between $177641 and $390307.4. The range of the price is quite wide but it is not so wide as to be useless.</p>
<p>To make the model become more useful, I can add more variable to the model like Year.Built variable (in project 2, it increases the value of <span class="math inline">\(R^2\)</span> a lot). And we can 95% confidence that the price of the house that built in 1990 with 2000 squared feet in Somerst is between $198957.1 and $335430.4. The gap between the price is much lesser than the model am2 which is $136473.3 while the am2 is $212666.4 which means that the new model can be more useful than the log(SalePrice)~Gr.Liv.Area + Neighborhood model.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 267193.7 198957.1 335430.4</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 136473.3</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 212666.4</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span>(<span class="fu">lm</span>(length<span class="sc">~</span>sex<span class="sc">+</span>birthmonth, <span class="at">data=</span>KidsFeet))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = length ~ sex + birthmonth, data = KidsFeet)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.75065 -0.71966 -0.09623  0.77202  2.41133 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 25.143094   0.487602  51.565   &lt;2e-16 ***
sexG        -0.786398   0.414238  -1.898   0.0657 .  
birthmonth  -0.006047   0.062385  -0.097   0.9233    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.291 on 36 degrees of freedom
Multiple R-squared:  0.09101,   Adjusted R-squared:  0.04051 
F-statistic: 1.802 on 2 and 36 DF,  p-value: 0.1795</code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>